"use client";

import Image from "next/image";
import { Metadata } from "next";
import { useState, useMemo } from "react";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { usePathname } from 'next/navigation'
import Link from "next/link";
import { shuffleWithSeed } from "@/lib/utils";

interface ImageProps{
  id: number;
  type: string;
  src: string;
  alt: string;
  width: number;
  height: number;
  }

const images = [
  // Graduation Images
  {
    id: 1,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad1.jpg",
    alt: "Graduation Picture 1",
    width: 500,
    height: 750,
  },
  {
    id: 2,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad2.jpg",
    alt: "Graduation Picture 2",
    width: 500,
    height: 750,
  },
  {
    id: 3,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad3.jpg",
    alt: "Graduation Picture 3",
    width: 500,
    height: 750,
  },
  {
    id: 4,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad4.jpg",
    alt: "Graduation Picture 4",
    width: 500,
    height: 750,
  },
  {
    id: 5,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad5.jpg",
    alt: "Graduation Picture 5",
    width: 500,
    height: 750,
  },
  {
    id: 6,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad6.jpg",
    alt: "Graduation Picture 6",
    width: 500,
    height: 750,
  },
  /*{
    id: 7,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad7.jpg",
    alt: "Graduation Picture 7",
    width: 500,
    height: 750,
  },
  {
    id: 8,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad8.jpg",
    alt: "Graduation Picture 8",
    width: 500,
    height: 750,
  },
  {
    id: 9,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad9.jpg",
    alt: "Graduation Picture 9",
    width: 500,
    height: 750,
  },
  {
    id: 10,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad10.jpg",
    alt: "Graduation Picture 10",
    width: 500,
    height: 750,
  },
  {
    id: 11,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad11.jpg",
    alt: "Graduation Picture 11",
    width: 500,
    height: 750,
  },
  {
    id: 12,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad12.jpg",
    alt: "Graduation Picture 12",
    width: 500,
    height: 750,
  },*/
  {
    id: 13,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad13.jpg",
    alt: "Graduation Picture 13",
    width: 500,
    height: 750,
  },
  {
    id: 14,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad14.jpg",
    alt: "Graduation Picture 14",
    width: 500,
    height: 750,
  },
  {
    id: 15,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad15.jpg",
    alt: "Graduation Picture 15",
    width: 500,
    height: 750,
  },
  /*{
    id: 16,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad16.jpg",
    alt: "Graduation Picture 16",
    width: 500,
    height: 750,
  },*/
  {
    id: 17,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad17.jpg",
    alt: "Graduation Picture 17",
    width: 500,
    height: 750,
  },
  {
    id: 18,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad18.jpg",
    alt: "Graduation Picture 18",
    width: 500,
    height: 750,
  },
  {
    id: 19,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad19.jpg",
    alt: "Graduation Picture 19",
    width: 500,
    height: 750,
  },
  {
    id: 20,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad20.jpg",
    alt: "Graduation Picture 20",
    width: 500,
    height: 750,
  },
  {
    id: 21,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad21.jpg",
    alt: "Graduation Picture 21",
    width: 500,
    height: 750,
  },
  {
    id: 22,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad22.jpg",
    alt: "Graduation Picture 22",
    width: 500,
    height: 750,
  },
  {
    id: 23,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad23.jpg",
    alt: "Graduation Picture 23",
    width: 500,
    height: 750,
  },
  {
    id: 24,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad24.jpg",
    alt: "Graduation Picture 24",
    width: 500,
    height: 750,
  },
  {
    id: 25,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad25.jpg",
    alt: "Graduation Picture 25",
    width: 500,
    height: 750,
  },
  {
    id: 26,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad26.jpg",
    alt: "Graduation Picture 26",
    width: 500,
    height: 750,
  },
  {
    id: 27,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad27.jpg",
    alt: "Graduation Picture 27",
    width: 500,
    height: 750,
  },
  {
    id: 28,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad28.jpg",
    alt: "Graduation Picture 28",
    width: 500,
    height: 750,
  },
  {
    id: 29,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad29.jpg",
    alt: "Graduation Picture 29",
    width: 500,
    height: 750,
  },
  {
    id: 30,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad30.jpg",
    alt: "Graduation Picture 30",
    width: 500,
    height: 750,
  },
  {
    id: 31,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad31.jpg",
    alt: "Graduation Picture 31",
    width: 500,
    height: 750,
  },
  {
    id: 32,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad32.jpg",
    alt: "Graduation Picture 32",
    width: 500,
    height: 750,
  },
  {
    id: 33,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad33.jpg",
    alt: "Graduation Picture 33",
    width: 500,
    height: 750,
  },
  {
    id: 34,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad34.jpg",
    alt: "Graduation Picture 34",
    width: 500,
    height: 750,
  },
  {
    id: 35,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad35.jpg",
    alt: "Graduation Picture 35",
    width: 500,
    height: 750,
  },
  {
    id: 36,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad36.jpg",
    alt: "Graduation Picture 36",
    width: 500,
    height: 750,
  },
  {
    id: 37,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad37.jpg",
    alt: "Graduation Picture 37",
    width: 500,
    height: 750,
  },
  {
    id: 38,
    type: "graduation",
    src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/graduation/grad38.jpg",
    alt: "Graduation Picture 38",
    width: 500,
    height: 750,
  },



  // Portraits Images
  /*{
      id: 39,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port1.jpg",
      alt: "Portrait Picture 1",
      width: 500,
      height: 750,
    },
    {
      id: 40,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port2.jpg",
      alt: "Portrait Picture 2",
      width: 500,
      height: 750,
    },*/
    {
      id: 41,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port3.jpg",
      alt: "Portrait Picture 3",
      width: 500,
      height: 750,
    },
    {
      id: 42,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port4.jpg",
      alt: "Portrait Picture 4",
      width: 500,
      height: 750,
    },
    /*{
      id: 43,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port5.jpg",
      alt: "Portrait Picture 5",
      width: 500,
      height: 750,
    },
    {
      id: 44,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port5.jpg",
      alt: "Portrait Picture 5 (duplicate)",
      width: 500,
      height: 750,
    },
    {
      id: 45,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port6.jpg",
      alt: "Portrait Picture 6",
      width: 500,
      height: 750,
    },
    {
      id: 46,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port7.jpg",
      alt: "Portrait Picture 7",
      width: 500,
      height: 750,
    },
    {
      id: 47,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port8.jpg",
      alt: "Portrait Picture 8",
      width: 500,
      height: 750,
    },
    {
      id: 48,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port9.jpg",
      alt: "Portrait Picture 9",
      width: 500,
      height: 750,
    },
    {
      id: 49,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port10.jpg",
      alt: "Portrait Picture 10",
      width: 500,
      height: 750,
    },*/
    {
      id: 50,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port11.jpg",
      alt: "Portrait Picture 11",
      width: 500,
      height: 750,
    },
    {
      id: 51,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port12.jpg",
      alt: "Portrait Picture 12",
      width: 500,
      height: 750,
    },
    /*{
      id: 52,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port13.jpg",
      alt: "Portrait Picture 13",
      width: 500,
      height: 750,
    },
    {
      id: 53,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port14.jpg",
      alt: "Portrait Picture 14",
      width: 500,
      height: 750,
    },
    {
      id: 54,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port15.jpg",
      alt: "Portrait Picture 15",
      width: 500,
      height: 750,
    },*/
    {
      id: 55,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port16.jpg",
      alt: "Portrait Picture 16",
      width: 500,
      height: 750,
    },
    /*{
      id: 56,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port17.jpg",
      alt: "Portrait Picture 17",
      width: 500,
      height: 750,
    },*/
    {
      id: 57,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port18.jpg",
      alt: "Portrait Picture 18",
      width: 500,
      height: 750,
    },
    {
      id: 58,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port19.jpg",
      alt: "Portrait Picture 19",
      width: 500,
      height: 750,
    },
    {
      id: 59,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port20.jpg",
      alt: "Portrait Picture 20",
      width: 500,
      height: 750,
    },
    {
      id: 60,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port21.jpg",
      alt: "Portrait Picture 21",
      width: 500,
      height: 750,
    },
    /*{
      id: 61,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port22.jpg",
      alt: "Portrait Picture 22",
      width: 500,
      height: 750,
    },
    {
      id: 62,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port23.jpg",
      alt: "Portrait Picture 23",
      width: 500,
      height: 750,
    },*/
    {
      id: 63,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port24.jpg",
      alt: "Portrait Picture 24",
      width: 500,
      height: 750,
    },
    /*{
      id: 64,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port25.jpg",
      alt: "Portrait Picture 25",
      width: 500,
      height: 750,
    },
    {
      id: 65,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port26.jpg",
      alt: "Portrait Picture 26",
      width: 500,
      height: 750,
    },*/
    {
      id: 66,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port27.jpg",
      alt: "Portrait Picture 27",
      width: 500,
      height: 750,
    },
    {
      id: 67,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port28.jpg",
      alt: "Portrait Picture 28",
      width: 500,
      height: 750,
    },
    {
      id: 68,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port29.jpg",
      alt: "Portrait Picture 29",
      width: 500,
      height: 750,
    },
    {
      id: 69,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port30.jpg",
      alt: "Portrait Picture 30",
      width: 500,
      height: 750,
    },
    /*{
      id: 70,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port31.jpg",
      alt: "Portrait Picture 31",
      width: 500,
      height: 750,
    },
    {
      id: 71,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port32.jpg",
      alt: "Portrait Picture 32",
      width: 500,
      height: 750,
    },*/
    {
      id: 72,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port33.jpg",
      alt: "Portrait Picture 33",
      width: 500,
      height: 750,
    },
    {
      id: 73,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port34.jpg",
      alt: "Portrait Picture 34",
      width: 500,
      height: 750,
    },
    {
      id: 74,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port35.jpg",
      alt: "Portrait Picture 35",
      width: 500,
      height: 750,
    },
    {
      id: 75,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port36.jpg",
      alt: "Portrait Picture 36",
      width: 500,
      height: 750,
    },
    /*{
      id: 76,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port37.jpg",
      alt: "Portrait Picture 37",
      width: 500,
      height: 750,
    },
    {
      id: 77,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port38.jpg",
      alt: "Portrait Picture 38",
      width: 500,
      height: 750,
    },*/
    {
      id: 78,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port39.jpg",
      alt: "Portrait Picture 39",
      width: 500,
      height: 750,
    },
    {
      id: 79,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port40.jpg",
      alt: "Portrait Picture 40",
      width: 500,
      height: 750,
    },
    /*{
      id: 80,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port41.jpg",
      alt: "Portrait Picture 41",
      width: 500,
      height: 750,
    },
    {
      id: 81,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port42.jpg",
      alt: "Portrait Picture 42",
      width: 500,
      height: 750,
    },*/
    {
      id: 82,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port43.jpg",
      alt: "Portrait Picture 43",
      width: 500,
      height: 750,
    },
    {
      id: 83,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port44.jpg",
      alt: "Portrait Picture 44",
      width: 500,
      height: 750,
    },
    /*{
      id: 84,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port45.jpg",
      alt: "Portrait Picture 45",
      width: 500,
      height: 750,
    },*/
    {
      id: 85,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port46.jpg",
      alt: "Portrait Picture 46",
      width: 500,
      height: 750,
    },
    /*{
      id: 86,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port47.jpg",
      alt: "Portrait Picture 47",
      width: 500,
      height: 750,
    },
    {
      id: 87,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port48.jpg",
      alt: "Portrait Picture 48",
      width: 500,
      height: 750,
    },*/
    {
      id: 88,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port49.jpg",
      alt: "Portrait Picture 49",
      width: 500,
      height: 750,
    },
    {
      id: 89,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port50.jpg",
      alt: "Portrait Picture 50",
      width: 500,
      height: 750,
    },
    {
      id: 90,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port51.jpg",
      alt: "Portrait Picture 51",
      width: 500,
      height: 750,
    },
    {
      id: 91,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port52.jpg",
      alt: "Portrait Picture 52",
      width: 500,
      height: 750,
    },
    {
      id: 92,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port53.jpg",
      alt: "Portrait Picture 53",
      width: 500,
      height: 750,
    },
    {
      id: 93,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port54.jpg",
      alt: "Portrait Picture 54",
      width: 500,
      height: 750,
    },
    {
      id: 94,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port55.jpg",
      alt: "Portrait Picture 55",
      width: 500,
      height: 750,
    },
    {
      id: 95,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port56.jpg",
      alt: "Portrait Picture 56",
      width: 500,
      height: 750,
    },
    {
      id: 96,
      type: "portraits",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/portraits/port57.jpg",
      alt: "Portrait Picture 57",
      width: 500,
      height: 750,
    },



    // Headshots Images
    {
      id: 97,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head1.jpg",
      alt: "Professional Headshot 1",
      width: 500,
      height: 750,
    },
    /*{
      id: 98,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head2.jpg",
      alt: "Professional Headshot 2",
      width: 500,
      height: 750,
    },
    {
      id: 99,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head3.jpg",
      alt: "Professional Headshot 3",
      width: 500,
      height: 750,
    },*/
    {
      id: 100,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head4.jpg",
      alt: "Professional Headshot 4",
      width: 500,
      height: 750,
    },
    /*{
      id: 101,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head5.jpg",
      alt: "Professional Headshot 5",
      width: 500,
      height: 750,
    },
    {
      id: 102,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head6.jpg",
      alt: "Professional Headshot 6",
      width: 500,
      height: 750,
    },
    {
      id: 103,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head7.jpg",
      alt: "Professional Headshot 7",
      width: 500,
      height: 750,
    },
    {
      id: 104,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head8.jpg",
      alt: "Professional Headshot 8",
      width: 500,
      height: 750,
    },*/
    {
      id: 105,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head9.jpg",
      alt: "Professional Headshot 9",
      width: 500,
      height: 750,
    },
    {
      id: 106,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head10.jpg",
      alt: "Professional Headshot 10",
      width: 500,
      height: 750,
    },
    {
      id: 107,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head11.jpg",
      alt: "Professional Headshot 11",
      width: 500,
      height: 750,
    },
    {
      id: 108,
      type: "headshots",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/headshots/head12.jpg",
      alt: "Professional Headshot 12",
      width: 500,
      height: 750,
    },



    // Events Images
    /*{
      id: 109,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event1.jpg",
      alt: "Event Picture 1",
      width: 500,
      height: 750,
    },
    {
      id: 110,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event2.jpg",
      alt: "Event Picture 2",
      width: 500,
      height: 750,
    },
    {
      id: 111,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event3.jpg",
      alt: "Event Picture 3",
      width: 500,
      height: 750,
    },*/
    {
      id: 112,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event4.jpg",
      alt: "Event Picture 4",
      width: 500,
      height: 750,
    },
    /*{
      id: 113,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event5.jpg",
      alt: "Event Picture 5",
      width: 500,
      height: 750,
    },
    {
      id: 114,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event6.jpg",
      alt: "Event Picture 6",
      width: 500,
      height: 750,
    },
    {
      id: 115,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event7.jpg",
      alt: "Event Picture 7",
      width: 500,
      height: 750,
    },
    {
      id: 116,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event8.jpg",
      alt: "Event Picture 8",
      width: 500,
      height: 750,
    },*/
    {
      id: 117,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event9.jpg",
      alt: "Event Picture 9",
      width: 500,
      height: 750,
    },
   /*{
      id: 118,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event10.jpg",
      alt: "Event Picture 10",
      width: 500,
      height: 750,
    },
    {
      id: 119,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event11.jpg",
      alt: "Event Picture 11",
      width: 500,
      height: 750,
    },
    {
      id: 120,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event12.jpg",
      alt: "Event Picture 12",
      width: 500,
      height: 750,
    },
    {
      id: 121,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event13.jpg",
      alt: "Event Picture 13",
      width: 500,
      height: 750,
    },
    {
      id: 122,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event14.jpg",
      alt: "Event Picture 14",
      width: 500,
      height: 750,
    },
    {
      id: 123,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event15.jpg",
      alt: "Event Picture 15",
      width: 500,
      height: 750,
    },
    {
      id: 124,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event16.jpg",
      alt: "Event Picture 16",
      width: 500,
      height: 750,
    },
    {
      id: 125,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event17.jpg",
      alt: "Event Picture 17",
      width: 500,
      height: 750,
    },
    {
      id: 126,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event18.jpg",
      alt: "Event Picture 18",
      width: 500,
      height: 750,
    },
    {
      id: 127,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event19.jpg",
      alt: "Event Picture 19",
      width: 500,
      height: 750,
    },
    {
      id: 128,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event20.jpg",
      alt: "Event Picture 20",
      width: 500,
      height: 750,
    },
    {
      id: 129,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event21.jpg",
      alt: "Event Picture 21",
      width: 500,
      height: 750,
    },
    {
      id: 130,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event22.jpg",
      alt: "Event Picture 22",
      width: 500,
      height: 750,
    },*/
    {
      id: 131,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event23.jpg",
      alt: "Event Picture 23",
      width: 500,
      height: 750,
    },
    /*{
      id: 132,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event24.jpg",
      alt: "Event Picture 24",
      width: 500,
      height: 750,
    },
    {
      id: 133,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event25.jpg",
      alt: "Event Picture 25",
      width: 500,
      height: 750,
    },
    {
      id: 134,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event26.jpg",
      alt: "Event Picture 26",
      width: 500,
      height: 750,
    },
    {
      id: 135,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event27.jpg",
      alt: "Event Picture 27",
      width: 500,
      height: 750,
    },
    {
      id: 136,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event28.jpg",
      alt: "Event Picture 28",
      width: 500,
      height: 750,
    },
    {
      id: 137,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event29.jpg",
      alt: "Event Picture 29",
      width: 500,
      height: 750,
    },
    {
      id: 138,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event30.jpg",
      alt: "Event Picture 30",
      width: 500,
      height: 750,
    },
    {
      id: 139,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event31.jpg",
      alt: "Event Picture 31",
      width: 500,
      height: 750,
    },
    {
      id: 140,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event32.jpg",
      alt: "Event Picture 32",
      width: 500,
      height: 750,
    },
    {
      id: 141,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event33.jpg",
      alt: "Event Picture 33",
      width: 500,
      height: 750,
    },
    {
      id: 142,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event34.jpg",
      alt: "Event Picture 34",
      width: 500,
      height: 750,
    },*/
    {
      id: 143,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event35.jpg",
      alt: "Event Picture 35",
      width: 500,
      height: 750,
    },
    {
      id: 144,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event36.jpg",
      alt: "Event Picture 36",
      width: 500,
      height: 750,
    },
    /*{
      id: 145,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event37.jpg",
      alt: "Event Picture 37",
      width: 500,
      height: 750,
    },
    {
      id: 146,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event38.jpg",
      alt: "Event Picture 38",
      width: 500,
      height: 750,
    },
    {
      id: 147,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event39.jpg",
      alt: "Event Picture 39",
      width: 500,
      height: 750,
    },
    {
      id: 148,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event40.jpg",
      alt: "Event Picture 40",
      width: 500,
      height: 750,
    },
    {
      id: 149,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event41.jpg",
      alt: "Event Picture 41",
      width: 500,
      height: 750,
    },*/
    {
      id: 150,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event42.jpg",
      alt: "Event Picture 42",
      width: 500,
      height: 750,
    },
    /*{
      id: 151,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event43.jpg",
      alt: "Event Picture 43",
      width: 500,
      height: 750,
    },
    {
      id: 152,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event44.jpg",
      alt: "Event Picture 44",
      width: 500,
      height: 750,
    },*/
    {
      id: 153,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event45.jpg",
      alt: "Event Picture 45",
      width: 500,
      height: 750,
    },
    /*{
      id: 154,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event46.jpg",
      alt: "Event Picture 46",
      width: 500,
      height: 750,
    },*/
    {
      id: 155,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event47.jpg",
      alt: "Event Picture 47",
      width: 500,
      height: 750,
    },
    /*{
      id: 156,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event48.jpg",
      alt: "Event Picture 48",
      width: 500,
      height: 750,
    },
    {
      id: 157,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event49.jpg",
      alt: "Event Picture 49",
      width: 500,
      height: 750,
    },
    {
      id: 158,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event50.jpg",
      alt: "Event Picture 50",
      width: 500,
      height: 750,
    },
    {
      id: 159,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event51.jpg",
      alt: "Event Picture 51",
      width: 500,
      height: 750,
    },
    {
      id: 160,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event52.jpg",
      alt: "Event Picture 52",
      width: 500,
      height: 750,
    },
    {
      id: 161,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event53.jpg",
      alt: "Event Picture 53",
      width: 500,
      height: 750,
    },
    {
      id: 162,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event54.jpg",
      alt: "Event Picture 54",
      width: 500,
      height: 750,
    },
    {
      id: 163,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event55.jpg",
      alt: "Event Picture 55",
      width: 500,
      height: 750,
    },
    {
      id: 164,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event56.jpg",
      alt: "Event Picture 56",
      width: 500,
      height: 750,
    },*/
    {
      id: 165,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event57.jpg",
      alt: "Event Picture 57",
      width: 500,
      height: 750,
    },
    /*{
      id: 166,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event58.jpg",
      alt: "Event Picture 58",
      width: 500,
      height: 750,
    },
    {
      id: 167,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event59.jpg",
      alt: "Event Picture 59",
      width: 500,
      height: 750,
    },
    {
      id: 168,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event60.jpg",
      alt: "Event Picture 60",
      width: 500,
      height: 750,
    },
    {
      id: 169,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event61.jpg",
      alt: "Event Picture 61",
      width: 500,
      height: 750,
    },
    {
      id: 170,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event62.jpg",
      alt: "Event Picture 62",
      width: 500,
      height: 750,
    },
    {
      id: 171,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event63.jpg",
      alt: "Event Picture 63",
      width: 500,
      height: 750,
    },
    {
      id: 172,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event64.jpg",
      alt: "Event Picture 64",
      width: 500,
      height: 750,
    },*/
    {
      id: 173,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event65.jpg",
      alt: "Event Picture 65",
      width: 500,
      height: 750,
    },
    /*{
      id: 174,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event66.jpg",
      alt: "Event Picture 66",
      width: 500,
      height: 750,
    },*/
    {
      id: 175,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event67.jpg",
      alt: "Event Picture 67",
      width: 500,
      height: 750,
    },
    /*{
      id: 176,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event68.jpg",
      alt: "Event Picture 68",
      width: 500,
      height: 750,
    },
    {
      id: 177,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event69.jpg",
      alt: "Event Picture 69",
      width: 500,
      height: 750,
    },
    {
      id: 178,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event70.jpg",
      alt: "Event Picture 70",
      width: 500,
      height: 750,
    },
    {
      id: 179,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event71.jpg",
      alt: "Event Picture 71",
      width: 500,
      height: 750,
    },
    {
      id: 180,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event72.jpg",
      alt: "Event Picture 72",
      width: 500,
      height: 750,
    },
    {
      id: 181,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event73.jpg",
      alt: "Event Picture 73",
      width: 500,
      height: 750,
    },*/
    {
      id: 182,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event74.jpg",
      alt: "Event Picture 74",
      width: 500,
      height: 750,
    },
    /*{
      id: 183,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event75.jpg",
      alt: "Event Picture 75",
      width: 500,
      height: 750,
    },
    {
      id: 184,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event76.jpg",
      alt: "Event Picture 76",
      width: 500,
      height: 750,
    },
    {
      id: 185,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event77.jpg",
      alt: "Event Picture 77",
      width: 500,
      height: 750,
    },
    {
      id: 186,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event78.jpg",
      alt: "Event Picture 78",
      width: 500,
      height: 750,
    },
    {
      id: 187,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event79.jpg",
      alt: "Event Picture 79",
      width: 500,
      height: 750,
    },
    {
      id: 188,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event80.jpg",
      alt: "Event Picture 80",
      width: 500,
      height: 750,
    },*/
    {
      id: 189,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event81.jpg",
      alt: "Event Picture 81",
      width: 500,
      height: 750,
    },
    /*{
      id: 190,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event82.jpg",
      alt: "Event Picture 82",
      width: 500,
      height: 750,
    },
    {
      id: 191,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event83.jpg",
      alt: "Event Picture 83",
      width: 500,
      height: 750,
    },
    {
      id: 192,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event84.jpg",
      alt: "Event Picture 84",
      width: 500,
      height: 750,
    },*/
    {
      id: 193,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event85.jpg",
      alt: "Event Picture 85",
      width: 500,
      height: 750,
    },
    {
      id: 194,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event86.jpg",
      alt: "Event Picture 86",
      width: 500,
      height: 750,
    },
    {
      id: 195,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event87.jpg",
      alt: "Event Picture 87",
      width: 500,
      height: 750,
    },
    {
      id: 196,
      type: "events",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/event/event88.jpg",
      alt: "Event Picture 88",
      width: 500,
      height: 750,
    },



    // Landscape & Architecture Images
    {
      id: 197,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land1.jpg",
      alt: "Landscape & Architecture Picture 1",
      width: 500,
      height: 750,
    },
    {
      id: 198,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land2.jpg",
      alt: "Landscape & Architecture Picture 2",
      width: 500,
      height: 750,
    },
    {
      id: 199,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land3.jpg",
      alt: "Landscape & Architecture Picture 3",
      width: 500,
      height: 750,
    },
    {
      id: 200,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land4.jpg",
      alt: "Landscape & Architecture Picture 4",
      width: 500,
      height: 750,
    },
    {
      id: 201,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land5.jpg",
      alt: "Landscape & Architecture Picture 5",
      width: 500,
      height: 750,
    },
    {
      id: 202,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land6.jpg",
      alt: "Landscape & Architecture Picture 6",
      width: 500,
      height: 750,
    },
    {
      id: 203,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land7.jpg",
      alt: "Landscape & Architecture Picture 7",
      width: 500,
      height: 750,
    },
    {
      id: 204,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land8.jpg",
      alt: "Landscape & Architecture Picture 8",
      width: 500,
      height: 750,
    },
    {
      id: 205,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land9.jpg",
      alt: "Landscape & Architecture Picture 9",
      width: 500,
      height: 750,
    },
    {
      id: 206,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land10.jpg",
      alt: "Landscape & Architecture Picture 10",
      width: 500,
      height: 750,
    },
    {
      id: 207,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land11.jpg",
      alt: "Landscape & Architecture Picture 11",
      width: 500,
      height: 750,
    },
    {
      id: 208,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land12.jpg",
      alt: "Landscape & Architecture Picture 12",
      width: 500,
      height: 750,
    },
    {
      id: 209,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land13.jpg",
      alt: "Landscape & Architecture Picture 13",
      width: 500,
      height: 750,
    },
    {
      id: 210,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land14.jpg",
      alt: "Landscape & Architecture Picture 14",
      width: 500,
      height: 750,
    },
    {
      id: 211,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land15.jpg",
      alt: "Landscape & Architecture Picture 15",
      width: 500,
      height: 750,
    },
    {
      id: 212,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land16.jpg",
      alt: "Landscape & Architecture Picture 16",
      width: 500,
      height: 750,
    },
    {
      id: 213,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land17.jpg",
      alt: "Landscape & Architecture Picture 17",
      width: 500,
      height: 750,
    },
    {
      id: 214,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land18.jpg",
      alt: "Landscape & Architecture Picture 18",
      width: 500,
      height: 750,
    },
    {
      id: 215,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land19.jpg",
      alt: "Landscape & Architecture Picture 19",
      width: 500,
      height: 750,
    },
    {
      id: 216,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land20.jpg",
      alt: "Landscape & Architecture Picture 20",
      width: 500,
      height: 750,
    },
    {
      id: 217,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land21.jpg",
      alt: "Landscape & Architecture Picture 21",
      width: 500,
      height: 750,
    },
    {
      id: 218,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land22.jpg",
      alt: "Landscape & Architecture Picture 22",
      width: 500,
      height: 750,
    },
    {
      id: 219,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land23.jpg",
      alt: "Landscape & Architecture Picture 23",
      width: 500,
      height: 750,
    },
    {
      id: 220,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land24.jpg",
      alt: "Landscape & Architecture Picture 24",
      width: 500,
      height: 750,
    },
    {
      id: 221,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land25.jpg",
      alt: "Landscape & Architecture Picture 25",
      width: 500,
      height: 750,
    },
    {
      id: 222,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land26.jpg",
      alt: "Landscape & Architecture Picture 26",
      width: 500,
      height: 750,
    },
    {
      id: 223,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land27.jpg",
      alt: "Landscape & Architecture Picture 27",
      width: 500,
      height: 750,
    },
    {
      id: 224,
      type: "landscape&architecture",
      src: "https://raw.githubusercontent.com/OODemi52/photogImages/main/landscape/land28.jpg",
      alt: "Landscape & Architecture Picture 28",
      width: 500,
      height: 750,
    },
];


export default function GalleryOption() {
  const pathname = usePathname();
  const lastSegment = pathname.split("/").pop();
  let category = decodeURI(usePathname().split("/").pop() ?? '').charAt(0).toUpperCase() + decodeURI(usePathname().split("/").pop() ?? '').slice(1);

  const filteredImages = images.filter((image) => image.type === lastSegment);

  const seed = 12345;
  const shuffledImages = useMemo(() => shuffleWithSeed([...filteredImages], seed), [filteredImages, seed]);

  const [open, setOpen] = useState(false);
  const [selectedImage, setSelectedImage] = useState<ImageProps | null>(null);

  const handleImageClick = (image: ImageProps) => {
    setSelectedImage(image);
    setOpen(true);
  };

  const _metadata: Metadata = {
    title: `D-Labs Photography - ${category === "Landscape&architecture" ? "Landscape & Architecture" : category} Gallery`,
    openGraph: {
      url: `https://dlabs.photo/gallery/${category === "Landscape&architecture" ? "Landscape & Architecture" : category}`,
      images: [
        {
          width: 512,
          height: 512,
          url: "https://raw.githubusercontent.com/OODemi52/photog/main/public/favicons/android-chrome-512x512.png",
        },
      ],
    },
  };

  return (
    <main>
      <h1 className="text-5xl pl-8 pt-4 font-thin">
        <Link href="/gallery" className="hover:underline">All</Link> {'>'} {category === "Landscape&architecture" ? "Landscape & Architecture" : category}
      </h1>
      <div className="gallery grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 p-4">
        {shuffledImages.map((image) => (
          <div key={image.id} className="gallery-item my-auto" onClick={() => handleImageClick(image)}>
            <Image
              src={image.src}
              alt={image.alt}
              width={image.width}
              height={image.height}
              className="rounded-lg shadow-lg"
              loading="lazy"
              quality={75}
            />
          </div>
        ))}
      </div>

      {selectedImage && (
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogContent>
            <Image
              src={selectedImage.src}
              alt={selectedImage.alt}
              width={selectedImage.width}
              height={selectedImage.height}
              className="rounded-lg shadow-lg"
              quality={100}
            />
          </DialogContent>
        </Dialog>
      )}
    </main>
  );
}